apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-w7xs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jtyi-tenant/rhtap-demo-app/hacbs-test-project-w7xs@sha256:ee1952054ba6aac46e1c56f082f7eff49ec2d4763839abbca7eafaeb029c3ae8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
